FROM python:3.12-slim AS builder

WORKDIR /app

# Копируем только файл зависимостей для кэширования слоя
COPY requirements.txt .

# Устанавливаем зависимости в специальную папку /install, а не в системную
RUN pip install --no-cache-dir -r requirements.txt --target=/install

# Финальный легкий образ
FROM python:3.12-slim AS final

WORKDIR /app

# Копируем установленные зависимости из этапа builder
COPY --from=builder /install /usr/local/lib/python3.12/site-packages/
# Копируем бинарные файлы (uvicorn и др.)
COPY --from=builder /install/bin/* /usr/local/bin/
# Копируем исходный код
COPY . .

# Открываем порт для uvicorn
EXPOSE 5000

# Команда запуска
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]
